### ISSUE TITLE
Fallback in Transport in client.js

### ISSUE THREAD

**Issue by HAPPYS1NGH** [HAPPYS1NGH/Arbitrum-Faucet#1]
# Description
If a Transport request fails, it will fall back to the next one in the list.

#Tasks

- [ ] Create Keys on Alchemy/Infura/BlastAPI for Goerli
- [ ] Create Keys on Alchemy/Infura/BlastAPI for Sepolia
- [ ] Create Keys on Alchemy/Infura/BlastAPI for Stylus
- [ ] Add the links in the clint.js

## Example
`
const client = createPublicClient({
  chain: arbitrum,
  transport: fallback([alchemy, infura]),
})
`

**Comment by Huyhihihi** [comment]
Hi, can I assign to this issue?

**Comment by HAPPYS1NGH** [comment]
Yes, but we need to prevent the API Key from being Public. After writing the code we can discuss on how to add the Environment Variables.

**Comment by HAPPYS1NGH** [comment]
#7 Done
