### ISSUE TITLE
Create Routes for Faucets info

### ISSUE THREAD

**Issue by HAPPYS1NGH** [HAPPYS1NGH/Arbitrum-Faucet#2]
# Description
Fetch the Faucet details like Address, Last transaction time and Funds Available in the Faucet.

# Tasks

- [x] Find out the wallet address of the faucets
- [x] Fetch the details from the wallet 
- [x] 1. Funds
- [x] 2. Last Active Time
- [x] Do the same for Sepolia
- [x] Do the same for Stylus 
- [x]  Extract the latest transaction Timestamp - If more than week Red
- [x] Extract the current Balance - If Zero Red
- [x] Check Can we make a get call and get the Address from the Semantic search Faucet pages.

# How

Explore alchemy SDK to fetch the transactions.

// Setup: npm install alchemy-sdk
import { Alchemy, Network } from "alchemy-sdk";

const config = {
  apiKey: "demo",
  network: Network.ETH_MAINNET,
};
const alchemy = new Alchemy(config);

// Address we want get NFT mints from
const toAddress = "0x1E6E8695FAb3Eb382534915eA8d7Cc1D1994B152";

const res = await alchemy.core.getAssetTransfers({
  fromBlock: "0x0",
  fromAddress: "0x0000000000000000000000000000000000000000",
  excludeZeroValue: true,
  category: ["erc721", "erc1155"],
});

console.log(res);

**Comment by HAPPYS1NGH** [comment]
Completed it
But using Etherscan and Arbiscan instead of Alchemy SDK

**Comment by HAPPYS1NGH** [comment]
Done in #16
