### ISSUE TITLE
Create a DBMS for Faucets

### ISSUE THREAD

**Issue by HAPPYS1NGH** [HAPPYS1NGH/Arbitrum-Faucet#3]
# Description
Currently, the faucet data is stored as a constant in the index.js file. We need to move on to a database system in the future to avoid complexity and manually adding each faucet. 

# Implementation
I a planning to do it with PostgreSQL for the database and Prisma as an ORM. (Open to more discussion)

# Tasks
- [ ] Initialise the repository with dependencies
- [ ] Create Schemas for Faucets
- [ ] Create API Routes to talk with Database
- [ ] Populate the data on Frontend after fetching it

**Comment by HAPPYS1NGH** [comment]
I dont think it is needed. It will just add complexity so Keeping it simple
